StoreApp/Components/CartSummaryViewComponent.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            _cart = cartService;
        }

        public string Invoke(){
            return _cart.Lines.Count.ToString();
        }
    }
}

StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace StoreApp.Components
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager; // !

        public ProductSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public string Invoke(){
            return  _manager.ProductService.GetAllProducts(false).Count().ToString();
        }
    }
}

StoreApp/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Entities.Models;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class CategoryController : Controller
    {
        private IServiceManager _manager;

        public CategoryController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.CategoryService.GetAllCategories(false); 
            return View(model);
        }
    }
}

StoreApp/Controllers/ProductController.cs
using System.Collections;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Entities.Models;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;
using Entities.RequestParameters;
using StoreApp.Models;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index(ProductRequestParameters p){
            var products = _manager.ProductService.GetAllProductsWithDetails(p);
            var pagination = new Pagination(){
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.ProductService.GetAllProducts(false).Count()
            };
            return View(new ProductListViewModel(){
                Products = products,
                Pagination = pagination
            });
        }

        public IActionResult Get([FromRoute(Name = "id")] int id){
            var model = _manager.ProductService.GetOneProduct(id, false);
            Product product = model ?? new Product();
            ViewData["Title"] = product?.ProductName;
            return View(product);
        }

    }
}

StoreApp/Views/Shared/_Footer.cshtml
<div class="bg-light border-top p-3">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="lead text-center">
                    <i class="fa fa-solid fa-store text-secondary display-6"></i>
                    <br>
                    <bold>Amazing</bold> Store
                </div>
                <div class="text-muted text-center">
                    Store App
                </div>
            </div>
            <div class="col-md-8">
                <div class="text-center text-muted my-3">
                    &copy; 2024 <br> Anil Karadag
                </div>
                <div class="text-center">
                    <div class="btn-group">
                        <a href="https://www.linkedin.com/in/alianilkaradag/" target="_blank" class="btn btn-secondary">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                        <a href="https://www.youtube.com/&#64;anl5460" target="_blank" class="btn btn-secondary">
                            <i class="fa-brands fa-youtube"></i>
                        </a>
                        <a href="https://www.instagram.com/anilkrd_?igsh=MTQ5eHJ0YjhpbGhiZw==" target="_blank" class="btn btn-secondary">
                            <i class="fa-brands fa-instagram"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div products="" number="6"></div>
            </div>
        </div>
    </div>
</div>

StoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StoreApp @ViewData["Title"]</title>
    <link rel="stylesheet" asp-append-version="true" href="~/lib/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" asp-append-version="true" href="~/css/site.css">
    <link rel="stylesheet" asp-append-version="true" href="~/lib/font-awesome/css/all.css">
</head>

<body>
    <header>
        <partial name="_Navbar"> </partial>
        @RenderSection("Header", false)
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        <partial name="_Footer"></partial>
    </footer>
    <script asp-append-version="true" src="~/lib/jquery/jquery.min.js"></script>
    <script asp-append-version="true" src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script asp-append-version="true" src="~/js/site.js"></script>
    <script asp-append-version="true" src="~/lib/font-awesome/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts", false)
</body>

</html>

StoreApp/Views/Shared/_LoginMenu.cshtml
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <li class="nav-item">
        <a class="nav-link" aria-current="page" asp-area="Admin" asp-controller="Dashboard" asp-action="Index"
            asp-route-ReturnUrl="@Context.Request.PathAndQuery()">
            <i class="fa-solid fa-gear"></i>
            Admin</a>
    </li>
}

@if (User.Identity.IsAuthenticated)
{
    <a class="nav-link" aria-current="page" asp-area="" asp-controller="Account" asp-action="Logout"
        asp-route-ReturnUrl="@Context.Request.PathAndQuery()">
        <i class="fa-solid fa-right-to-bracket"></i>
        Logout</a>
}
else
{

    <li class="nav-item">
        <a class="nav-link" aria-current="page" asp-area="" asp-controller="Account" asp-action="Login"
            asp-route-ReturnUrl="@Context.Request.PathAndQuery()">
            <i class="fa-solid fa-right-to-bracket"></i>
            Login</a>
    </li>
}

StoreApp/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom">
  <div class="container">
    <a class="navbar-brand mb-0 h1" href="/">Store App</a>
    <i class="fa-solid fa-store fa-2x text-secondary"></i>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavAltMarkup">
      <ul class="navbar-nav flex-grow-1">
        <li>
          <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" asp-controller="Product" asp-action="Index">Products
            (@await Component.InvokeAsync("ProductSummary"))</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" asp-controller="Category" asp-action="Index">Categories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" asp-page="/Contact">Contact</a>
        </li>
      </ul>

      <ul class="navbar-nav text-white">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" asp-area="" asp-page="/Cart">
          <i class="fa-solid fa-cart-shopping"></i>
          Cart (@await Component.InvokeAsync("CartSummary"))
          </a>
        </li>
      
        <partial name="_LoginMenu"></partial>
      </ul>
    </div>
  </div>
</nav>

StoreApp/Views/Shared/_Notification.cshtml
@if (TempData["info"] is not null){
    <div class="alert alert-info my-3" role="alert">
        @TempData["info"]
    </div>
}
@if (TempData["success"] is not null){
    <div class="alert alert-success my-3" role="alert">
        @TempData["info"]
    </div>
}
@if (TempData["danger"] is not null){
    <div class="alert alert-danger my-3" role="alert">
        @TempData["danger"]
    </div>
}

StoreApp/Views/Shared/_ProductCard.cshtml
@model Product

<div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-4 my-2">
    <div class="card" style="width: 18rem;">
        <div class="card-header text-center">
            @Model.ProductName
        </div>
        <img src="@Model?.ImageUrl" class="card-img-top" alt="...">
        <div class="card-body">
            <div class="card-text">
                <div class="text-danger text-center lead p-2 rounded-2">
                    @Model?.Price.ToString("C2")
                </div>
            </div>

            <p class="card-text">@Model?.Summary</p>
            <div class="d-flex justify-content-center">
                <div class="btn btn-group">
                    <a asp-controller="Product" asp-action="Get" asp-route-id="@Model.ProductId"
                        class="btn btn-outline-secondary rounded-2">
                        <i class="fa-solid fa-arrow-right"></i>
                    </a>
                    <form id="@Model.ProductId" asp-page="/cart" method="post">
                        <input type="hidden" asp-for="ProductId" />
                        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                        <button class="btn btn-outline-secondary mx-1" type="submit">
                            <i class="fa fa-cart-plus"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>